# Generated by Django 4.1.6 on 2025-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, verbose_name='Срок возврата'),
        ),
    ]
